spring:
  application:
    name: Bank_SpringBoot
  datasource:
    url: jdbc:postgresql://localhost:5432/bank1
    username: postgres
    password: 89615786193z
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
debug: true
